// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: CYD_stepmotor

#include "ui.h"
#include "ui_helpers.h"
#include "stdio.h"

///////////////////// VARIABLES ////////////////////

float setDistance = 0;
unsigned int setCount = 0;

bool startNexit_flag = false;

bool HomeState = false;
bool resetState = false;


float Step[] = {1.0f ,10.0f,100.0f};
int decimal = 0;
int current_index = 0;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Container2;
void ui_event_Decrease(lv_event_t * e);
lv_obj_t * ui_Decrease;
void ui_event_Increase(lv_event_t * e);
lv_obj_t * ui_Increase;
lv_obj_t * ui_Label1;
void ui_event_notiBtn(lv_event_t * e);
lv_obj_t * ui_notiBtnOff;
lv_obj_t * ui_Container3;
void ui_event_Home(lv_event_t * e);
lv_obj_t * ui_Home;
void ui_event_Run(lv_event_t * e);
lv_obj_t * ui_Run;
lv_obj_t * ui_Stop;
void ui_event_Info(lv_event_t * e);
lv_obj_t * ui_Info;
lv_obj_t * ui_Panel1;
void ui_event_ImgButton7(lv_event_t * e);
lv_obj_t * ui_ImgButton7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label4;
void ui_event_StepDown(lv_event_t * e);
lv_obj_t * ui_StepDown;
void ui_event_StepUp(lv_event_t * e);
lv_obj_t * ui_StepUp;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Label5;
void ui_event_Bar1(lv_event_t * e);
lv_obj_t * ui_Bar1;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Panel5;
void ui_event_SetcountUp(lv_event_t * e);
lv_obj_t * ui_SetcountUp;
void ui_event_SetcountDown(lv_event_t * e);
lv_obj_t * ui_SetcountDown;
lv_obj_t * ui_Label7;
void ui_event_StartNexit(lv_event_t * e);
lv_obj_t * ui_StartNexit;
void ui_event_ImgButton3(lv_event_t * e);
lv_obj_t * ui_ImgButton3;
lv_obj_t * ui_Panel6;
void ui_event_ImgButton2(lv_event_t * e);
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui_Label10;
lv_obj_t * ui_TextArea1;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
/** Set Distance */
void updateDistance(int direction) { 

    static float lastDistance = -1;  // Save the previous value to avoid unnecessary UI updates.
    
    setDistance += direction * Step[current_index];  // direction = 1 (Up) | -1 (Dơwn)

    if (setDistance != lastDistance) {  // Only update the UI if the value changes.
        char buffer[50];
        snprintf(buffer, sizeof(buffer), "%.f MM", decimal, setDistance);
        _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, buffer);
        
        lastDistance = setDistance;  // Update new value
    }
}

void ui_event_Decrease(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {

        updateDistance(-1);  // Up
        
    }
}
void ui_event_Increase(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {

        updateDistance(1);  // Down
    }
}
/** //////////////////////////////////// */

/** For set Step fuction */
void updateStep(int direction) {  
    static float lastIndex = -1;  // Save the index to avoid unnecessary updates.

    current_index = (current_index + direction + 3) % 3;  // Add or subtract index.

    if (current_index != lastIndex) {  // Only update the UI if the value changes.
        decimal = current_index;  // Updated decimal

        char buffer[50];
        snprintf(buffer, sizeof(buffer), "%.f", decimal, Step[current_index]);
        _ui_label_set_property(ui_Label4, _UI_LABEL_PROPERTY_TEXT, buffer);

        lastIndex = current_index;  
    }
}

void ui_event_StepUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
       
        updateStep(1);

    }
}

void ui_event_StepDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {

       updateStep(-1); 
       

    }
}
/** ///////////////////////////////////// */

/** Go Home */
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        HomeState = true;

        char buffer[15]; 
        snprintf(buffer, sizeof(buffer), "Goto Home");
        lv_textarea_set_text(ui_TextArea1, buffer);

        lv_imagebutton_set_src(ui_notiBtnOff, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_bellgreen_png, NULL);
    }
}
/** ////////////////////// */
/** Reset */
void ui_event_Reset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {

    lv_imagebutton_set_src(ui_notiBtnOff, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_bellpink_png, NULL);
    lv_bar_set_value(ui_Bar1, 0, LV_ANIM_ON);

    char buffer[15]; 
    snprintf(buffer, sizeof(buffer), "Cleaned!");
    lv_textarea_set_text(ui_TextArea1, buffer);
    
    setDistance = 0; 
    updateDistance(0);

    setCount = 0;
    updateCount(0); 

    lv_label_set_text(ui_Label5, "0.0 mm");

    resetState = true;

    }
}
/** ///////////////////////////// */
/** For set Count fuction */
void updateCount(int direction) {  

    static unsigned int lastCount = 0; 

    setCount += direction;  

    if (setCount != lastCount) {  

        char buffer[50];
        snprintf(buffer, sizeof(buffer), "%u", (int)setCount);
        _ui_label_set_property(ui_Label7, _UI_LABEL_PROPERTY_TEXT, buffer);

        lastCount = setCount; 
    }
}
void ui_event_SetcountUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        updateCount(1);
    }
}

void ui_event_SetcountDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {

        updateCount(-1);
    }
}

/** //////////////////////////////////////////////// */
/** Tab confirm */
void ui_event_Run(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
/** ////////////////////////////// */

/** Show notification */
void ui_event_notiBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_Panel6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      
        
    }
}
/** ///////////////////////////////////// */

/** Show Info */
void ui_event_Info(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
/** Exit info tab */
void ui_event_ImgButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
/** //////////////////////////////////////////// */
/** Display bar */
void ui_event_Bar1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label5, target, "", "");
    }
}
/** /////////////////////////// */
/** Start and exit confirm tab*/
void ui_event_StartNexit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
         startNexit_flag = true;
         lv_imagebutton_set_src(ui_notiBtnOff, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_bellgreen_png, NULL);
    }
}
/** /////////////////////////////// */
/** Exit confirm tab or info tab*/
void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);

    }
}
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_Panel6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
/** /////////////////////////////////////////////////// */

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
