// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: CYD_stepmotor

#ifndef _CYD_STEPMOTOR_UI_H
#define _CYD_STEPMOTOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"



// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container2;
void ui_event_Decrease(lv_event_t * e);
extern lv_obj_t * ui_Decrease;
void ui_event_Increase(lv_event_t * e);
extern lv_obj_t * ui_Increase;
extern lv_obj_t * ui_Label1;
void ui_event_notiBtn(lv_event_t * e);
extern lv_obj_t * ui_notiBtnOff;
extern lv_obj_t * ui_Container3;
void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
void ui_event_Run(lv_event_t * e);
extern lv_obj_t * ui_Run;
void ui_event_Reset(lv_event_t * e);
extern lv_obj_t * ui_Stop;
void ui_event_Info(lv_event_t * e);
extern lv_obj_t * ui_Info;
extern lv_obj_t * ui_Panel1;
void ui_event_ImgButton7(lv_event_t * e);
extern lv_obj_t * ui_ImgButton7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label4;
void ui_event_StepDown(lv_event_t * e);
extern lv_obj_t * ui_StepDown;
void ui_event_StepUp(lv_event_t * e);
extern lv_obj_t * ui_StepUp;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label5;
void ui_event_Bar1(lv_event_t * e);
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel5;
void ui_event_SetcountUp(lv_event_t * e);
extern lv_obj_t * ui_SetcountUp;
void ui_event_SetcountDown(lv_event_t * e);
extern lv_obj_t * ui_SetcountDown;
extern lv_obj_t * ui_Label7;
void ui_event_StartNexit(lv_event_t * e);
extern lv_obj_t * ui_StartNexit;
void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Panel6;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui____initial_actions0;

extern float setDistance;
extern unsigned int setCount;
extern float Step[];
extern int decimal;
extern int current_index;

extern bool startNexit_flag;
extern bool Notification;

extern bool resetState;
extern bool HomeState;

// extern bool countUp;
// extern bool countDown;

// extern bool confirm;
// extern bool home;
// extern bool run;
// extern bool stop;


LV_IMG_DECLARE(ui_img_decrease_png);    // assets/decrease.png
LV_IMG_DECLARE(ui_img_plus_png);    // assets/plus.png
LV_IMG_DECLARE(ui_img_bellslient_png);   
LV_IMG_DECLARE(ui_img_bellpink_png);    
LV_IMG_DECLARE(ui_img_bellgreen_png);   
LV_IMG_DECLARE(ui_img_square_home_png);    // assets/square_home.png
LV_IMG_DECLARE(ui_img_arrowfwrpng_png);    // assets/arrowFWRpng.png
LV_IMG_DECLARE(ui_img_reset_png);    // assets/Reset.png
LV_IMG_DECLARE(ui_img_squareinfo_png);    // assets/squareInfo.png
LV_IMG_DECLARE(ui_img_exit_png);    // assets/exit.png
LV_IMG_DECLARE(youtubeqr);    // assets/youtube.png
LV_IMG_DECLARE(githubqr);    // assets/githubIcon.png
LV_IMG_DECLARE(bmcqr);    // assets/youtube.png
LV_IMG_DECLARE(ui_img_arrowdwn_png);    // assets/arrowDwn.png
LV_IMG_DECLARE(ui_img_arrowup_png);    // assets/arrowUp.png
LV_IMG_DECLARE(ui_img_location_png);    // assets/location.png
LV_IMG_DECLARE(ui_img_btnstart_png);    // assets/btnStart.png


void ui_init(void);
void updateDistance(int direction);
void updateStep(int direction);
void updateCount(int direction);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
