// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: CYD_stepmotor

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 311);
    lv_obj_set_height(ui_Container2, 60);
    lv_obj_set_x(ui_Container2, -2);
    lv_obj_set_y(ui_Container2, -64);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Decrease = lv_imagebutton_create(ui_Container2);
    lv_imagebutton_set_src(ui_Decrease, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_decrease_png, NULL);
    lv_obj_set_width(ui_Decrease, 32);
    lv_obj_set_height(ui_Decrease, 32);
    lv_obj_set_x(ui_Decrease, -137);
    lv_obj_set_y(ui_Decrease, 1);
    lv_obj_set_align(ui_Decrease, LV_ALIGN_CENTER);

    ui_Increase = lv_imagebutton_create(ui_Container2);
    lv_imagebutton_set_src(ui_Increase, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_plus_png, NULL);
    lv_obj_set_width(ui_Increase, 32);
    lv_obj_set_height(ui_Increase, 32);
    lv_obj_set_x(ui_Increase, 56);
    lv_obj_set_y(ui_Increase, 1);
    lv_obj_set_align(ui_Increase, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -40);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "MM");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFF12AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notiBtnOff = lv_imagebutton_create(ui_Container2);
    lv_imagebutton_set_src(ui_notiBtnOff, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_bellslient_png, NULL);
    lv_obj_set_height(ui_notiBtnOff, 32);
    lv_obj_set_width(ui_notiBtnOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_notiBtnOff, 120);
    lv_obj_set_y(ui_notiBtnOff, 0);
    lv_obj_set_align(ui_notiBtnOff, LV_ALIGN_CENTER);

    ui_Container3 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 313);
    lv_obj_set_height(ui_Container3, 67);
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, 80);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Home = lv_imagebutton_create(ui_Container3);
    lv_imagebutton_set_src(ui_Home, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_square_home_png, NULL);
    lv_obj_set_height(ui_Home, 64);
    lv_obj_set_width(ui_Home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Home, -119);
    lv_obj_set_y(ui_Home, 0);
    lv_obj_set_align(ui_Home, LV_ALIGN_CENTER);

    ui_Run = lv_imagebutton_create(ui_Container3);
    lv_imagebutton_set_src(ui_Run, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_arrowfwrpng_png, NULL);
    lv_obj_set_height(ui_Run, 64);
    lv_obj_set_width(ui_Run, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Run, -39);
    lv_obj_set_y(ui_Run, 1);
    lv_obj_set_align(ui_Run, LV_ALIGN_CENTER);

    ui_Stop = lv_imagebutton_create(ui_Container3);
    lv_imagebutton_set_src(ui_Stop, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_reset_png, NULL);
    lv_obj_set_height(ui_Stop, 64);
    lv_obj_set_width(ui_Stop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Stop, 120);
    lv_obj_set_y(ui_Stop, 1);
    lv_obj_set_align(ui_Stop, LV_ALIGN_CENTER);

    ui_Info = lv_imagebutton_create(ui_Container3);
    lv_imagebutton_set_src(ui_Info, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_squareinfo_png, NULL);
    lv_obj_set_width(ui_Info, 64);
    lv_obj_set_height(ui_Info, 64);
    lv_obj_set_x(ui_Info, 41);
    lv_obj_set_y(ui_Info, 1);
    lv_obj_set_align(ui_Info, LV_ALIGN_CENTER);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 309);
    lv_obj_set_height(ui_Panel1, 140);
    lv_obj_set_x(ui_Panel1, -1);
    lv_obj_set_y(ui_Panel1, -25);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xCCFFE2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x488B23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton7 = lv_imagebutton_create(ui_Panel1);
    lv_imagebutton_set_src(ui_ImgButton7, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_exit_png, NULL);
    lv_obj_set_height(ui_ImgButton7, 25);
    lv_obj_set_width(ui_ImgButton7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton7, 138);
    lv_obj_set_y(ui_ImgButton7, -53);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);

    ui_Label8 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -10);
    lv_obj_set_y(ui_Label8, -54);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Stepmotor Control Panel");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x1424FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel7, 284);
    lv_obj_set_height(ui_Panel7, 102);
    lv_obj_set_x(ui_Panel7, 2);
    lv_obj_set_y(ui_Panel7, 12);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_Panel7);
    lv_image_set_src(ui_Image3, &youtubeqr);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -89);
    lv_obj_set_y(ui_Image3, -5);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Panel7);
    lv_image_set_src(ui_Image1, &githubqr);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 89);
    lv_obj_set_y(ui_Image1, -5);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Panel7);
    lv_image_set_src(ui_Image2, &bmcqr);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, -5);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    

    ui_Label9 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 73);
    lv_obj_set_y(ui_Label9, 42);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Open Source - Ver: 1.0.25");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFF007B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 144);
    lv_obj_set_height(ui_Panel2, 47);
    lv_obj_set_x(ui_Panel2, -83);
    lv_obj_set_y(ui_Panel2, -3);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFBDBFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "0");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x3800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StepDown = lv_imagebutton_create(ui_Panel2);
    lv_imagebutton_set_src(ui_StepDown, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_arrowdwn_png, NULL);
    lv_obj_set_height(ui_StepDown, 24);
    lv_obj_set_width(ui_StepDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_StepDown, -52);
    lv_obj_set_y(ui_StepDown, 0);
    lv_obj_set_align(ui_StepDown, LV_ALIGN_CENTER);

    ui_StepUp = lv_imagebutton_create(ui_Panel2);
    lv_imagebutton_set_src(ui_StepUp, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_arrowup_png, NULL);
    lv_obj_set_width(ui_StepUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_StepUp, 51);
    lv_obj_set_y(ui_StepUp, 1);
    lv_obj_set_align(ui_StepUp, LV_ALIGN_CENTER);
    lv_obj_set_style_transform_rotation(ui_StepUp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 139);
    lv_obj_set_height(ui_Panel3, 46);
    lv_obj_set_x(ui_Panel3, 84);
    lv_obj_set_y(ui_Panel3, -3);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xCFFDFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_Panel3);
    lv_image_set_src(ui_Image4, &ui_img_location_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -48);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 15);
    lv_obj_set_y(ui_Label5, -1);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "0.0 mm");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFF6D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 305);
    lv_obj_set_height(ui_Bar1, 15);
    lv_obj_set_x(ui_Bar1, -2);
    lv_obj_set_y(ui_Bar1, -108);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xE086FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Bar1, lv_color_hex(0xFF736B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Bar1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar1,
                                                                                           lv_obj_get_style_pad_right(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 283);
    lv_obj_set_height(ui_Panel4, 110);
    lv_obj_set_x(ui_Panel4, -1);
    lv_obj_set_y(ui_Panel4, -22);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xC0FEF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel4, lv_color_hex(0x4551FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -6);
    lv_obj_set_y(ui_Label6, -38);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Set Count & Press Start");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x0938F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel5, 128);
    lv_obj_set_height(ui_Panel5, 44);
    lv_obj_set_x(ui_Panel5, -49);
    lv_obj_set_y(ui_Panel5, 19);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xC5E3FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetcountUp = lv_imagebutton_create(ui_Panel5);
    lv_imagebutton_set_src(ui_SetcountUp, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_arrowup_png, NULL);
    lv_obj_set_height(ui_SetcountUp, 24);
    lv_obj_set_width(ui_SetcountUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_SetcountUp, -46);
    lv_obj_set_y(ui_SetcountUp, 0);
    lv_obj_set_align(ui_SetcountUp, LV_ALIGN_CENTER);

    ui_SetcountDown = lv_imagebutton_create(ui_Panel5);
    lv_imagebutton_set_src(ui_SetcountDown, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_arrowdwn_png, NULL);
    lv_obj_set_height(ui_SetcountDown, 24);
    lv_obj_set_width(ui_SetcountDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_SetcountDown, 45);
    lv_obj_set_y(ui_SetcountDown, 0);
    lv_obj_set_align(ui_SetcountDown, LV_ALIGN_CENTER);

    ui_Label7 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "0");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xF800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartNexit = lv_imagebutton_create(ui_Panel4);
    lv_imagebutton_set_src(ui_StartNexit, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btnstart_png, NULL);
    lv_obj_set_height(ui_StartNexit, 64);
    lv_obj_set_width(ui_StartNexit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_StartNexit, 86);
    lv_obj_set_y(ui_StartNexit, 18);
    lv_obj_set_align(ui_StartNexit, LV_ALIGN_CENTER);

    ui_ImgButton3 = lv_imagebutton_create(ui_Panel4);
    lv_imagebutton_set_src(ui_ImgButton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_exit_png, NULL);
    lv_obj_set_height(ui_ImgButton3, 24);
    lv_obj_set_width(ui_ImgButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton3, 124);
    lv_obj_set_y(ui_ImgButton3, -36);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 312);
    lv_obj_set_height(ui_Panel6, 128);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, -28);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFEFB9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel6, lv_color_hex(0xFB0E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imagebutton_create(ui_Panel6);
    lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_exit_png, NULL);
    lv_obj_set_height(ui_ImgButton2, 23);
    lv_obj_set_width(ui_ImgButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton2, 140);
    lv_obj_set_y(ui_ImgButton2, -49);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_Label10 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -96);
    lv_obj_set_y(ui_Label10, -47);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Notification");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x071BFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_Panel6);
    lv_obj_set_width(ui_TextArea1, 302);
    lv_obj_set_height(ui_TextArea1, 89);
    lv_obj_set_x(ui_TextArea1, 0);
    lv_obj_set_y(ui_TextArea1, 13);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "No notification");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Nothing here");
    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xC82DFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_notiBtnOff, ui_event_notiBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Run, ui_event_Run, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Info, ui_event_Info, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton7, ui_event_ImgButton7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Bar1, ui_event_Bar1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StartNexit, ui_event_StartNexit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetcountUp, ui_event_SetcountUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetcountDown, ui_event_SetcountDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Decrease, ui_event_Decrease, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Increase, ui_event_Increase, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home, ui_event_Home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Stop, ui_event_Reset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StepDown, ui_event_StepDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StepUp, ui_event_StepUp, LV_EVENT_ALL, NULL);

}
